### ISSUE TITLE
Workflow erroring but it still checks out

### ISSUE THREAD

**Issue by J3fftw1** [axel-op/googlejavaformat-action#10]
Im trying to set the workflow length it gives an error but the workflow still succeeds. 
My args are  ```args: "--replace --aosp --length=100"``` 

i have tried -length 100, --length 100, -length=100 and --length=100

im also doing something wrong with the length cant figure out why though.
this is the link to the job where it shows the error https://github.com/J3fftw1/LiteXpansion/pull/103/checks?check_run_id=1288203565

If you need any more info let me know also really like this workflow thanks for making it <3

**Comment by axel-op** [comment]
Hi,

By looking at your workflow run, I see there is an error message:

```
partial formatting is only support for a single file
```

So using this argument will probably not work with multiple files.

Hope this helps :)

**Comment by J3fftw1** [comment]
Ah okay will there be support for multiple files in the future
And the work flow should have failed instead of completed on the error thats where this bug report was made for actually and also a little help

**Comment by axel-op** [comment]
This limitation actually comes from [google-java-format](https://github.com/google/google-java-format) itself, it's not specific to this action (you can test it on your local machine to see that it will still be there). You'll have to open an issue in their repo to propose this feature.

If the action successfully completes without an error, that's because the GJF executable doesn't terminate with an error code, even though there is one indeed...
