### ISSUE TITLE
WARNING: An illegal reflective access operation has occurred

### ISSUE THREAD

**Issue by PrimeDominus** [axel-op/googlejavaformat-action#16]
First time user here. I get the following. Is this due to the Github action or something else I should be looking at?

WARNING: An illegal reflective access operation has occurred
WARNING: Illegal reflective access by com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer (file:/home/runner/google-java-format.jar) to field com.sun.tools.javac.parser.JavaTokenizer.reader
WARNING: Please consider reporting this to the maintainers of com.google.googlejavaformat.java.JavacTokens$CommentSavingTokenizer
WARNING: Use --illegal-access=warn to enable warnings of further illegal reflective access operations

**Comment by PrimeDominus** [comment]
This using Ubuntu 20.04.2 LTS and JDK 11

Run axel-op/googlejavaformat-action@v3
  with:
    args: --skip-sorting-imports --replace
    files: **/*.java
    skipCommit: false
    commitMessage: Google Java Format

**Comment by axel-op** [comment]
Hi @PrimeDominus,

Thanks for the issue. This is a warning emitted because the Google program uses reflection to access an encapsulated class. Since JDK9 packages that aren't opened to reflection cannot be accessed this way, except by libraries that have not been modularized yet, as it is the case for the Google one.

I don't know why it appeared only recently, and I'll try to "fix" it by using the workaround described [here](https://github.com/google/google-java-format#jdk-16).

Note that this is just a warning and that does not mean that this action is broken: you can ignore it.

**Comment by PrimeDominus** [comment]
@axel-op thank you :smile 

By "fix" do you mean applying the following?

```
java \ --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \ --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \ --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \ --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \ --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \ -jar google-java-format-1.11.0-all-deps.jar <options> [files...]
```

**Comment by axel-op** [comment]
> @axel-op thank you
> 
> By "fix" do you mean applying the following?
> 
> ```
> java \
>   --add-exports jdk.compiler/com.sun.tools.javac.api=ALL-UNNAMED \
>   --add-exports jdk.compiler/com.sun.tools.javac.file=ALL-UNNAMED \
>   --add-exports jdk.compiler/com.sun.tools.javac.parser=ALL-UNNAMED \
>   --add-exports jdk.compiler/com.sun.tools.javac.tree=ALL-UNNAMED \
>   --add-exports jdk.compiler/com.sun.tools.javac.util=ALL-UNNAMED \
>   -jar google-java-format-1.11.0-all-deps.jar <options> [files...]
> ```

Yes... With commit 4ac8f4d763cf6a0dae5829e25b2e8a7c0d7d8790 these exports will automatically be applied, and these warnings won't show up anymore!
